export const useCourse = () => {
	return [
		'Bachelor of Computer Science (Cyber Security) with Honours',
		'Bachelor of Computer Science (Software Engineering) with Honours',
		'Bachelor of Computer Science (Multimedia Software) with Honours',
		'Bachelor of Computer Science (Computer Systems & Networking) with Honours',
		'Bachelor of Automotive Engineering with Honours',
		'Bachelor of Mechatronics Engineering with Honours',
		'Bachelor of Electrical Engineering (Electronics) with Honours',
		'Bachelor of Business Engineering With Honours',
		'Bachelor of Civil Engineering with Honours',
		'Bachelor of Chemical Engineering with Honours',
		'Bachelor of Electrical Engineering with Honours',
		'Bachelor of Manufacturing Engineering with Honours',
		'B.Eng (Hons.) Mechatronics Engineering',
		'Bachelor of Mechanical Engineering with Honours',
		'Bachelor of Chemical Engineering Technology With Hons.',
		'Bachelor of Manufacturing Engineering Technology (Pharmaceutical) With Hons.',
		'Bachelor of Mechanical Engineering Technology (Petroleum) With Honours',
		'Bachelor of Civil Engineering Technology (Building) With Honours',
		'Bachelor of Engineering Technology (Infrastructure Management) With Hons.',
		'Bachelor of Engineering Technology (Energy & Environmental) With Hons.',
		'Bachelor of Mechanical Engineering Technology (Automotive) with Honours',
		'Bachelor of Mechanical Engineering Technology (Oil and Gas) with Honours',
		'Bachelor of Mechanical Engineering Technology (Design and Analysis) with Honours',
		'Bachelor of Mechatronic Engineering Technology (Robotics) with Honours',
		'Bachelor of Manufacturing Engineering Technology (Industrial Automation) with Honours',
		'Bachelor of Manufacturing Engineering Technology (Advanced Manufacturing) with Honours',
		'Bachelor of Electronics Engineering Technology (Computer System) With Honours',
		'Bachelor of Electrical Engineering Technology (Energy) with Honours',
		'Bachelor of Applied Science in Industrial Biotechnology with Honours',
		'Bachelor of Applied Science in Industrial Chemistry with Honours',
		'Bachelor of Applied Science in Material Technology with Honours',
		'Bachelor of Applied Science in Data Analytics with Honours',
		'Bachelor of Occupational Safety & Health With Honours',
		'Bachelor of Business Analytics with Honours',
		'Bachelor of Project Management with Honours',
		'Bachelor of Industrial Technology Management with Honours',
		'Bachelor of Technology in Building Construction with Honours',
		'Bachelor of Technology in Automotive with Honours',
		'Bachelor of Technology in Industrial Electronic Automation with Honours',
		'Bachelor of Technology in Electrical System Maintenance with Honours',
		'Bachelor of Technology in Oil & Gas Facilities Maintenance with Honours',
		'Bachelor of Technology Industrial Machining with Honours',
		'Bachelor of Technology in Welding with Honours',
		'Diploma in Computer Science',
		'Diploma in Civil Engineering',
		'Diploma in Chemical Engineering',
		'Diploma in Mechanical Engineering',
		'Diploma in Electrical and Electronics Engineering',
		'Diploma in Manufacturing Engineering Technology',
		'Diploma in Industrial Sciences',
		'Diploma in Occupational Safety And Health'
	]
}
