export const usePosition = () => {
	return [
		'Vice-Chancellor',
		'Deputy Vice-Chancellor (Academic and International)',
		'Deputy Vice-Chancellor (Research and Innovation)',
		'Deputy Vice-Chancellor (Student Affairs and Alumni)',
		'Dean',
		'Deputy Dean (Academic)',
		'Deputy Dean (Student Affairs)',
		'Deputy Dean (Research and Innovation)',
		'Head of Department',
		'Senior Lecturer',
		'Lecturer',
		'Assistant Registrar',
		'Administrative Officer',
		'Librarian',
		'IT Officer',
		'Research Officer',
		'Technician',
		'Lab Assistant',
		'Student Counselor',
		'Public Relations Officer',
		'Financial Officer',
		'Safety Officer',
		'Audit Executive',
		'Facilities Manager',
		'Project Manager',
		'Welfare Officer',
		'Press Editor',
		'Disability Services Coordinator'
	]
}
